# Generated by Django 3.1.3 on 2020-11-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201125_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='New_Country',
        ),
        migrations.DeleteModel(
            name='New_Country',
        ),
    ]
